apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-example-yellow-deployment
  namespace: bluegreen-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-example
      version: v1
      color: yellow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bluegreen-example
        version: v1
        color: yellow
    spec:
      containers:
      - name: bluegreen-example-page-container
        image: docker.io/library/bluegreen-example:yellow-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always