apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-example-blue-deployment
  namespace: bluegreen-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-example
      version: v1
      color: blue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bluegreen-example
        version: v1
        color: blue
    spec:
      containers:
      - name: bluegreen-example-page-container
        image: docker.io/library/bluegreen-example:blue-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always