# Use an official nginx image as the base image
FROM nginx:alpine

# Copy the static HTML file to the nginx html directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to the outside world
EXPOSE 80
